runtime: nodejs
env: flex

runtime_config:
  nodejs_version: 14

env_variables:
  MY_VAR: my_value
  NODE_ENV: production

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
