runtime: nodejs14

env_variables:
  MY_VAR: my_value
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.5

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always
